# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/HIDToyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HIDToyWindow(object):
    def setupUi(self, HIDToyWindow):
        HIDToyWindow.setObjectName("HIDToyWindow")
        HIDToyWindow.resize(700, 600)
        HIDToyWindow.setMinimumSize(QtCore.QSize(700, 600))
        HIDToyWindow.setMaximumSize(QtCore.QSize(700, 600))
        self.centralwidget = QtWidgets.QWidget(HIDToyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boxReceiveData = QtWidgets.QGroupBox(self.centralwidget)
        self.boxReceiveData.setGeometry(QtCore.QRect(20, 280, 661, 261))
        self.boxReceiveData.setObjectName("boxReceiveData")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.boxReceiveData)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 641, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonReadInReport = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.buttonReadInReport.setObjectName("buttonReadInReport")
        self.horizontalLayout_5.addWidget(self.buttonReadInReport)
        self.buttonGetFeatureReport = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.buttonGetFeatureReport.setObjectName("buttonGetFeatureReport")
        self.horizontalLayout_5.addWidget(self.buttonGetFeatureReport)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.spinReportId = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinReportId.sizePolicy().hasHeightForWidth())
        self.spinReportId.setSizePolicy(sizePolicy)
        self.spinReportId.setMaximum(255)
        self.spinReportId.setProperty("value", 0)
        self.spinReportId.setObjectName("spinReportId")
        self.horizontalLayout_5.addWidget(self.spinReportId)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinSizeIn = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinSizeIn.sizePolicy().hasHeightForWidth())
        self.spinSizeIn.setSizePolicy(sizePolicy)
        self.spinSizeIn.setMinimum(1)
        self.spinSizeIn.setMaximum(128)
        self.spinSizeIn.setProperty("value", 64)
        self.spinSizeIn.setObjectName("spinSizeIn")
        self.horizontalLayout_5.addWidget(self.spinSizeIn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.textGetData = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textGetData.setObjectName("textGetData")
        self.verticalLayout_4.addWidget(self.textGetData)
        self.boxSendData = QtWidgets.QGroupBox(self.centralwidget)
        self.boxSendData.setGeometry(QtCore.QRect(20, 140, 661, 141))
        self.boxSendData.setObjectName("boxSendData")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.boxSendData)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 641, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboSendData = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboSendData.setEditable(True)
        self.comboSendData.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboSendData.setObjectName("comboSendData")
        self.verticalLayout_3.addWidget(self.comboSendData)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonSendOutReport = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.buttonSendOutReport.setEnabled(True)
        self.buttonSendOutReport.setObjectName("buttonSendOutReport")
        self.horizontalLayout_2.addWidget(self.buttonSendOutReport)
        self.buttonSendFeatureReport = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.buttonSendFeatureReport.setObjectName("buttonSendFeatureReport")
        self.horizontalLayout_2.addWidget(self.buttonSendFeatureReport)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spinSizeOut = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinSizeOut.setMinimum(1)
        self.spinSizeOut.setMaximum(128)
        self.spinSizeOut.setProperty("value", 64)
        self.spinSizeOut.setObjectName("spinSizeOut")
        self.horizontalLayout_2.addWidget(self.spinSizeOut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.boxDevices = QtWidgets.QGroupBox(self.centralwidget)
        self.boxDevices.setGeometry(QtCore.QRect(20, 50, 661, 91))
        self.boxDevices.setObjectName("boxDevices")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.boxDevices)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 641, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonReScan = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonReScan.sizePolicy().hasHeightForWidth())
        self.buttonReScan.setSizePolicy(sizePolicy)
        self.buttonReScan.setObjectName("buttonReScan")
        self.horizontalLayout.addWidget(self.buttonReScan)
        self.deviceList = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.deviceList.setObjectName("deviceList")
        self.horizontalLayout.addWidget(self.deviceList)
        self.buttonConnect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConnect.sizePolicy().hasHeightForWidth())
        self.buttonConnect.setSizePolicy(sizePolicy)
        self.buttonConnect.setObjectName("buttonConnect")
        self.horizontalLayout.addWidget(self.buttonConnect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(20, 10, 591, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setObjectName("labelTitle")
        self.attribution = QtWidgets.QLabel(self.centralwidget)
        self.attribution.setGeometry(QtCore.QRect(630, 540, 60, 16))
        self.attribution.setOpenExternalLinks(True)
        self.attribution.setObjectName("attribution")
        HIDToyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HIDToyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        HIDToyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HIDToyWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        HIDToyWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(HIDToyWindow)
        QtCore.QMetaObject.connectSlotsByName(HIDToyWindow)

    def retranslateUi(self, HIDToyWindow):
        _translate = QtCore.QCoreApplication.translate
        HIDToyWindow.setWindowTitle(_translate("HIDToyWindow", "HIDToy"))
        self.boxReceiveData.setTitle(_translate("HIDToyWindow", "Receive data:"))
        self.buttonReadInReport.setText(_translate("HIDToyWindow", "Read IN Reports"))
        self.buttonGetFeatureReport.setText(_translate("HIDToyWindow", "Get FEATURE Report"))
        self.label_10.setText(_translate("HIDToyWindow", "reportId:"))
        self.label_7.setText(_translate("HIDToyWindow", "reportSize:"))
        self.boxSendData.setTitle(_translate("HIDToyWindow", "Send data:"))
        self.buttonSendOutReport.setText(_translate("HIDToyWindow", "Send OUT Report"))
        self.buttonSendFeatureReport.setText(_translate("HIDToyWindow", "Send FEATURE Report"))
        self.label_6.setText(_translate("HIDToyWindow", "reportSize:"))
        self.label_8.setText(_translate("HIDToyWindow", "Send data format is Python list, e.g. \"1,99,0xff,0,0\". 1st byte is reportId (if using reportIds)"))
        self.boxDevices.setTitle(_translate("HIDToyWindow", "Devices:"))
        self.buttonReScan.setText(_translate("HIDToyWindow", "Rescan"))
        self.buttonConnect.setText(_translate("HIDToyWindow", "Connect"))
        self.labelTitle.setText(_translate("HIDToyWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">HIDPyToy</span> - List HID devices. Send data. Receive data. Use IN, OUT, or FEATURE reports!</p></body></html>"))
        self.attribution.setText(_translate("HIDToyWindow", "<html><head/><body><p>by <a href=\"https://github.com/todbot/hidpytoy/\"><span style=\" text-decoration: underline; color:#0000ff;\">todbot</span></a></p></body></html>"))
        self.menuFile.setTitle(_translate("HIDToyWindow", "File"))
        self.menuEdit.setTitle(_translate("HIDToyWindow", "Edit"))
        self.menuView.setTitle(_translate("HIDToyWindow", "View"))

