# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HIDToyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HIDToyWindow(object):
    def setupUi(self, HIDToyWindow):
        HIDToyWindow.setObjectName("HIDToyWindow")
        HIDToyWindow.resize(696, 550)
        self.centralwidget = QtWidgets.QWidget(HIDToyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boxReceiveData = QtWidgets.QGroupBox(self.centralwidget)
        self.boxReceiveData.setGeometry(QtCore.QRect(20, 310, 651, 191))
        self.boxReceiveData.setObjectName("boxReceiveData")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.boxReceiveData)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 631, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonGetReport = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGetReport.sizePolicy().hasHeightForWidth())
        self.buttonGetReport.setSizePolicy(sizePolicy)
        self.buttonGetReport.setObjectName("buttonGetReport")
        self.horizontalLayout_5.addWidget(self.buttonGetReport)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.spinReportId = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinReportId.sizePolicy().hasHeightForWidth())
        self.spinReportId.setSizePolicy(sizePolicy)
        self.spinReportId.setMaximum(255)
        self.spinReportId.setProperty("value", 0)
        self.spinReportId.setObjectName("spinReportId")
        self.horizontalLayout_5.addWidget(self.spinReportId)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinSizeIn = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinSizeIn.sizePolicy().hasHeightForWidth())
        self.spinSizeIn.setSizePolicy(sizePolicy)
        self.spinSizeIn.setMinimum(1)
        self.spinSizeIn.setMaximum(128)
        self.spinSizeIn.setProperty("value", 64)
        self.spinSizeIn.setObjectName("spinSizeIn")
        self.horizontalLayout_5.addWidget(self.spinSizeIn)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.buttonInTypeIn = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInTypeIn.sizePolicy().hasHeightForWidth())
        self.buttonInTypeIn.setSizePolicy(sizePolicy)
        self.buttonInTypeIn.setObjectName("buttonInTypeIn")
        self.horizontalLayout_5.addWidget(self.buttonInTypeIn)
        self.buttonInTypeFeature = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInTypeFeature.sizePolicy().hasHeightForWidth())
        self.buttonInTypeFeature.setSizePolicy(sizePolicy)
        self.buttonInTypeFeature.setChecked(True)
        self.buttonInTypeFeature.setObjectName("buttonInTypeFeature")
        self.horizontalLayout_5.addWidget(self.buttonInTypeFeature)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.textGetData = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textGetData.setObjectName("textGetData")
        self.verticalLayout_4.addWidget(self.textGetData)
        self.boxSendData = QtWidgets.QGroupBox(self.centralwidget)
        self.boxSendData.setGeometry(QtCore.QRect(20, 160, 651, 151))
        self.boxSendData.setObjectName("boxSendData")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.boxSendData)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 631, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonSendReport = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.buttonSendReport.setEnabled(True)
        self.buttonSendReport.setObjectName("buttonSendReport")
        self.horizontalLayout_2.addWidget(self.buttonSendReport)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spinSizeOut = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinSizeOut.sizePolicy().hasHeightForWidth())
        self.spinSizeOut.setSizePolicy(sizePolicy)
        self.spinSizeOut.setMinimum(1)
        self.spinSizeOut.setMaximum(128)
        self.spinSizeOut.setProperty("value", 64)
        self.spinSizeOut.setObjectName("spinSizeOut")
        self.horizontalLayout_2.addWidget(self.spinSizeOut)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.buttonOutTypeOut = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOutTypeOut.sizePolicy().hasHeightForWidth())
        self.buttonOutTypeOut.setSizePolicy(sizePolicy)
        self.buttonOutTypeOut.setObjectName("buttonOutTypeOut")
        self.horizontalLayout_2.addWidget(self.buttonOutTypeOut)
        self.buttonOutTypeFeature = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOutTypeFeature.sizePolicy().hasHeightForWidth())
        self.buttonOutTypeFeature.setSizePolicy(sizePolicy)
        self.buttonOutTypeFeature.setChecked(True)
        self.buttonOutTypeFeature.setObjectName("buttonOutTypeFeature")
        self.horizontalLayout_2.addWidget(self.buttonOutTypeFeature)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textSendData = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textSendData.sizePolicy().hasHeightForWidth())
        self.textSendData.setSizePolicy(sizePolicy)
        self.textSendData.setObjectName("textSendData")
        self.horizontalLayout_3.addWidget(self.textSendData)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.boxDevices = QtWidgets.QGroupBox(self.centralwidget)
        self.boxDevices.setGeometry(QtCore.QRect(20, 50, 651, 101))
        self.boxDevices.setObjectName("boxDevices")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.boxDevices)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 631, 60))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonReScan = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonReScan.sizePolicy().hasHeightForWidth())
        self.buttonReScan.setSizePolicy(sizePolicy)
        self.buttonReScan.setObjectName("buttonReScan")
        self.horizontalLayout.addWidget(self.buttonReScan)
        self.deviceList = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.deviceList.setObjectName("deviceList")
        self.horizontalLayout.addWidget(self.deviceList)
        self.buttonConnect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConnect.sizePolicy().hasHeightForWidth())
        self.buttonConnect.setSizePolicy(sizePolicy)
        self.buttonConnect.setObjectName("buttonConnect")
        self.horizontalLayout.addWidget(self.buttonConnect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(20, 20, 651, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setObjectName("labelTitle")
        HIDToyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HIDToyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        HIDToyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HIDToyWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        HIDToyWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(HIDToyWindow)
        QtCore.QMetaObject.connectSlotsByName(HIDToyWindow)

    def retranslateUi(self, HIDToyWindow):
        _translate = QtCore.QCoreApplication.translate
        HIDToyWindow.setWindowTitle(_translate("HIDToyWindow", "HIDToy"))
        self.boxReceiveData.setTitle(_translate("HIDToyWindow", "Receive data:"))
        self.buttonGetReport.setText(_translate("HIDToyWindow", "Get Report"))
        self.label_10.setText(_translate("HIDToyWindow", "reportId:"))
        self.label_7.setText(_translate("HIDToyWindow", "reportSize:"))
        self.label_9.setText(_translate("HIDToyWindow", "reportType:"))
        self.buttonInTypeIn.setText(_translate("HIDToyWindow", "  IN"))
        self.buttonInTypeFeature.setText(_translate("HIDToyWindow", "FEATURE"))
        self.boxSendData.setTitle(_translate("HIDToyWindow", "Send data:"))
        self.buttonSendReport.setText(_translate("HIDToyWindow", "Send Report"))
        self.label_6.setText(_translate("HIDToyWindow", "reportSize:"))
        self.label_4.setText(_translate("HIDToyWindow", "reportType:"))
        self.buttonOutTypeOut.setText(_translate("HIDToyWindow", "OUT"))
        self.buttonOutTypeFeature.setText(_translate("HIDToyWindow", "FEATURE"))
        self.label_8.setText(_translate("HIDToyWindow", "Data format is Python list, e.g. \"(1,99,0xff,0x00,0xff,0,0)\". First byte is reportId (if using reportIds)"))
        self.boxDevices.setTitle(_translate("HIDToyWindow", "Devices:"))
        self.buttonReScan.setText(_translate("HIDToyWindow", "Rescan"))
        self.buttonConnect.setText(_translate("HIDToyWindow", "Connect"))
        self.labelTitle.setText(_translate("HIDToyWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">HIDToy</span>  - List HID devices, Send and receive data to them</p></body></html>"))
        self.menuFile.setTitle(_translate("HIDToyWindow", "File"))
        self.menuEdit.setTitle(_translate("HIDToyWindow", "Edit"))
        self.menuView.setTitle(_translate("HIDToyWindow", "View"))

